name: flutter_job
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  firebase_analytics: ^10.8.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  intl: ^0.19.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/icon.png
